[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Common settings for all environments
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_DEBUG_LOGGING = "false"

# Production context
[context.production.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "production"
  VITE_SITE_URL = "https://partner.claygrounds.com"
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_DEBUG_LOGGING = "false"

# Development branch context
[context.development.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "development"
  VITE_SITE_URL = "https://development--claygroundspartner.netlify.app"
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_DEBUG_LOGGING = "true"

# Branch Deploy context
[context.branch-deploy.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "development"
  VITE_SITE_URL = "https://development--claygroundspartner.netlify.app"
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_DEBUG_LOGGING = "true"

# Deploy Preview context
[context.deploy-preview.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "development"
  VITE_SITE_URL = "https://development--claygroundspartner.netlify.app"
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_DEBUG_LOGGING = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "frame-ancestors 'none'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 