[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_APP_ENV = "production"
  VITE_ENABLE_MOCK_DATA = "false"
  VITE_ENABLE_DEBUG_LOGGING = "false"

# Production context
[context.production]
  environment = { 
    NODE_VERSION = "18"
    VITE_SITE_URL = "https://partner.claygrounds.com"
  }

# Deploy Preview context
[context.deploy-preview]
  environment = { 
    NODE_VERSION = "18"
    VITE_SITE_URL = "$DEPLOY_URL"
  }

# Branch Deploy context
[context.branch-deploy]
  environment = { 
    NODE_VERSION = "18"
    VITE_SITE_URL = "$DEPLOY_URL"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 